#!/bin/bash

# Functions
spacing() {
  for i in {1..$1}; do
    echo ""
  done
}

create_dir() {
  TYPE=$1
  PROJECT=$2 

  if [[ -z "$PROJECT" ]]; then
    echo "Please provide a project name"
    exit 2
  fi
  
  echo -e "PROJECT-TYPE:  $TYPE\n"
  echo -e "PROJECT-NAME:  $PROJECT\n"

  mkdir ./"$PROJECT" || echo "couldn't create directory"
  cd "$PROJECT" && echo -e "# $PROJECT\n" > README.md
}

init_repo() {
  vim README.md
  wait $!
  git init
}

# Main Script
TYPE=$1
NAME=$2

case "$TYPE" in
  "py-standard") 
  	  create_dir "$TYPE" "$NAME"
	  mkdir modules
	  touch main.py 
	  init_repo

	  ;;

  "py-flask") 
	  create_dir "$TYPE" "$NAME"
	  mkdir static templates views
	  touch ./static/style.css ./templates/index.html 
	  touch ./app.py ./config.py ./requirements.txt
	  init_repo

	  ;;

  "web") 
	  create_dir "$TYPE" "$NAME"
	  mkdir styles
	  touch index.html main.js
	  init_repo

	  ;;

  *)    exit 0           ;;
esac


