#!/bin/bash

if [[ ! "$(which gum 2>/dev/null)" ]]; then
  echo "Please install charmbracelet/gum"
fi

style() {
  gum style\
	  --border normal\
	  --width  40\
	  $1
}

spacing() {
  for i in {1..$1}; do
    echo ""
  done
}

create_dir() {
  mkdir ./"$PROJECT" || echo "couldn't create directory"
  cd "$PROJECT" && echo -e "# $PROJECT\n" > README.md
}

init_repo() {
  vim README.md
  wait $!
  git init
}

confirm() {
  spacing 3
  PROJECT="$(gum input --placeholder "Enter Project name")" 

  if [[ -z "$PROJECT" ]]; then
    echo "Please provide a project name"
    exit 2
  fi
  
  spacing 3
  echo -e "PROJECT-TYPE:  $TYPE\n"
  echo -e "PROJECT-NAME:  $PROJECT\n"

  gum confirm "Continue ?" || exit 0
}




gum style\
	  --border double\
	  --margin "1 2"\
	  --padding "1 2"\
	  "⚙ GEARHEAD "

spacing 3
TYPE="$(gum choose\
	  "PYTHON-standard"\
	  "PYTHON-flask-basic"\
	  "WEB"\
	  "EXIT"
	  )"


case "$TYPE" in
  "PYTHON-standard") 
	  confirm "$TYPE"
  	  create_dir
	  mkdir modules
	  touch main.py 
	  init_repo

	  ;;

  "PYTHON-flask-basic") 
	  confirm "$TYPE"
	  create_dir
	  mkdir static templates views
	  touch ./static/style.css ./templates/index.html 
	  touch ./app.py ./config.py ./requirements.txt
	  init_repo

	  ;;

  "WEB") 
	  confirm "$TYPE"
	  create_dir
	  mkdir styles
	  touch index.html main.js
	  init_repo

	  ;;

  *)    exit 0           ;;
esac


